import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend Mentor | [Challenge Name Here]",
  description: "Generated by create next app",
  icons: "/favicon-32x32.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
        <noscript>This Website Need JavaScript</noscript>
      </body>
    </html>
  );
}
